name: Issue Creation Tracker
on:
  issues:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Issue Details
      run: |
          echo "Issue creator: ${{ github.event.issue.user.login }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue url: ${{ github.event.issue.html_url }}"
          echo "Assigned labels: " ${{ join(github.event.issue.labels.*.name) }}
          echo "Assignees: " ${{ join(github.event.issue.assignees.*.login) }}
    - name: Install jq
      run: sudo apt-get install jq -y
    - name: Google Chat Notification
      env:
          TITLE: ${{ github.event.issue.title }}
      run: |
          PAYLOAD=$(jq -n --arg title "$TITLE" --arg login "${{ github.event.issue.user.login }}" --argjson labels "${{ github.event.issue.labels }}" --argjson assignees "${{ github.event.issue.assignees }}" '
          {
          cards: [
            {
              header: {
                title: "Issue Tracker",
                subtitle: "Issue No: #\($number)"
              },
              sections: [
                {
                  widgets: [
                    {
                      keyValue: {
                        topLabel: "Creator",
                        content: $login
                      }
                    },
                    {
                      keyValue: {
                        topLabel: "Title",
                        content: $title
                      }
                    },
                    {
                      keyValue: {
                        topLabel: "Assigned Labels",
                        content: ($labels | map("- " + .name) | join("\n"))
                      }
                    },
                    {
                      keyValue: {
                        topLabel: "Assignees",
                        content: ($assignees | map("- " + .login) | join("\n"))
                      }
                    },
                    {
                      buttons: [
                        {
                          textButton: {
                            text: "OPEN ISSUE",
                            onClick: {
                              openLink: {
                                url: $html_url
                              }
                            }
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
          }')
  
          curl --location --request POST '${{ secrets.INTERNAL_SUPPORT_ALERT }}' \
            --header 'Content-Type: application/json' \
            --data-raw "$PAYLOAD"
                    ]
                }'
